### PR TITLE
[Oracle] Added missing sharedlock Method (HTTP 500 otherwise)

### LINKED ISSUE #879: Fatal error: Class Phalcon\Db\Dialect\Oracle contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
Tengo tengo mi aplicacion trabajando de manera adecuada en la version de phalcon 3.4.1, pero al instalarla en otro servidor con la version 3.4.2 no trabaja, al intentar loguear mi aplicacion obtengo el siguiente mensaje:

Fatal error: Class Phalcon\Db\Dialect\Oracle contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Phalcon\Db\DialectInterface::sharedLock) in /var/www/html/boaplus/vendor/phalcon/incubator/Library/Phalcon/Db/Dialect/Oracle.php on line 612

estoy trabajando con oracle cliente 12.2
tengo un archivo php que trbaja con oracle 12.2 y este trabaja sin problemas, validando la corrcta instalacion de php y oci8 junto con el PDO_OCI

[root@localhost Dialect]# php -m | egrep -i "(oci|phalcon)"
oci8
PDO_OCI
phalcon

espero puedan apoyarme. saludos

### Details

* Phalcon Framework version: (
Version => 3.4.2)
Powered by Zephir => Version 0.10.10-d1b4cc68d9
* Phalcon Incubator version: (branch, composer version)
[root@localhost Dialect]# php -v
PHP 7.2.11 (cli) (built: Oct 10 2018 10:00:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

* Operating System: centOS/
* Server:Apache
* Other related info (Oracle, BOA):

### PR DESCRIPTION
**Pull request by lubber-de**
Hello!

* Type: bug fix

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR. (Existing test for Oracle can be used)

## Description
Since the DialectInterface implemented a new method `sharedLock`, the Oracle Dialect was not working anymore, because it misses the interface method `sharedLock` resulting in a HTTP 500 Server error when trying to query from the database.

```
PHP Fatal error:  Class Phalcon\\Db\\Dialect\\Oracle contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Phalcon\\Db\\DialectInterface::sharedLock)
```

## Closes
#879

### CODE REVIEW

File: Library/Phalcon/Db/Dialect/Oracle.php [hunk 1]
```diff
@@ -53,6 +53,16 @@ class Oracle extends Dialect
     protected $_escapeChar = "";
     // @codingStandardsIgnoreEnd
 
+    /**
+     * Returns a SQL modified with a LOCK IN SHARE MODE clause
+     *
+     * @param string $sqlQuery
+     * @return string
+     */
+    public function sharedLock($sqlQuery) {
```
Comment (sergeyklay) [inline Library/Phalcon/Db/Dialect/Oracle.php]:
```suggestion
    public function sharedLock($sqlQuery)
    {
```

Comment (sergeyklay) [inline Library/Phalcon/Db/Dialect/Oracle.php]:
```suggestion
    public function sharedLock($sqlQuery)
    {
```

**Comment by sergeyklay** [comment]
Thank you
